### ISSUE TITLE
Goland 2019.2.1 display wrong color for go code

### ISSUE THREAD

**Issue by Modificator** [arcticicestudio/nord-jetbrains#100]
GoLand 2019.2.1
Build #GO-192.6262.60, built on August 21, 2019
plugin version:0.8.1
![image](https://user-images.githubusercontent.com/3425930/64308482-fd825a80-cfcb-11e9-9ff6-e5b386bcb102.png)

**Comment by arcticicestudio** [comment]
Hi @Modificator :wave:

It might be that you're using a customized copy of _Nord_. When setting a color or UI theme that is provided by a plugin and editing any of the editor's code styles, the IDE will automatically create a copy of the theme with your modifications.
Can you please check if there's a `Nord` file in your configuration directory in the `colors` folder. You can find the path to the directory for your OS in the [official documentation about default IDE directories][d].

If there's a file named `Nord` (might have different file extensions) you need to delete it. Afterwards restart _GoLand_ and set _Nord_ as editor scheme again. This will use the styles provided by the plugin instead of using a (maybe outdated) copy.

[d]: https://www.jetbrains.com/help/idea/tuning-the-ide.html#default-dirs

**Comment by Modificator** [comment]
Thanks, it's working.
