### ISSUE TITLE
Poor contrast between 'added block' background and comments in comparison view

### ISSUE THREAD

**Issue by ratskinmahoney** [arcticicestudio/nord-jetbrains#103]
When using the comparison view, the contrast between the 'added block' background colour and the comment colour makes reading the comments difficult (or at least, uncomfortable). This particular background colour makes reading anything at least a little uncomfortable, and I tend to select-all in order to avoid it, but I find it most difficult with comments.

### Comments:
![Screenshot 2019-09-26 at 09 26 57](https://user-images.githubusercontent.com/2954690/65672338-c3dbc700-e040-11e9-8116-b1090dfcc3c7.png)

### General:
![Screenshot 2019-09-26 at 09 36 04](https://user-images.githubusercontent.com/2954690/65672502-1b7a3280-e041-11e9-9397-0a3e6380907e.png)

**Comment by arcticicestudio** [comment]
Hi @ratskinmahoney :wave:, thanks for your contribution :+1:
This was a known problem some years ago and was improved in #25, but I can see that this might be a problem. I currently not sure if you're using the latest version of the theme plugin since the comment color was also improved in #42 (released with [version 0.4.0][v]), but the color on your screenshots looks not like the updated one.

1. Please make sure **you're using the latest plugin version**.
2. Please check if **you're using a copy of the theme** which gets **automatically created by the IDE when a setting of the currently active editor or UI theme gets changed** by the user. You can follow the instructions I've posted in https://github.com/arcticicestudio/nord-jetbrains/issues/100#issuecomment-531490650 which also solved the problem for the user.

I'll also test the _diff_ view next time I push a PR. If this style is still used in the latest version, I think I'll [port the improved styles implemented for the VS Code theme][vscode].

[v]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.4.0
[vscode]: https://github.com/arcticicestudio/nord-visual-studio-code/pull/105

**Comment by ratskinmahoney** [comment]
Thanks for the prompt and detailed reply, @arcticicestudio.

The version of the plugin I'm using is 0.8.1 - apologies for missing this information out in the initial report:
![Screenshot 2019-09-27 at 08 13 09](https://user-images.githubusercontent.com/2954690/65749807-c866b500-e0fe-11e9-9bc0-35304d6e9b91.png)

I've followed the instructions in the comment you linked above:
- Navigated to '~/Library/Preferences/<app>/colors/' (I'm on mac)
- Removed '_@user_Nord.icls'
- Started IntelliJ Idea
- In settings switched theme away from Nord, applied, and then switched the theme back to Nord and applied

The colours still look the same, I'm afraid:
![Screenshot 2019-09-27 at 08 17 15](https://user-images.githubusercontent.com/2954690/65750014-4cb93800-e0ff-11e9-80ee-e6a8792d8d53.png)

I've also tried uninstalling and reinstalling the plugin, but with the same effect. Is there something I've missed out, or something else I can do to more thoroughly reset the theme?

**Comment by nmaves** [comment]
I am still seeing this issue as well with 11.2

**Comment by arcticicestudio** [comment]
This is still a pending topic one a large list, but everyone can feel free to submit a PR using the linked PR from the _VS Code_ port as reference. Unfortunately the proposal Microsoft/vscode#71663 was closed/not accepted to improve the theme API within _VS Code_ itself so I guess there's no other way around than adapting the adjusted styles from _Nord Visual Studio Code_.

**Comment by ratskinmahoney** [comment]
Thanks for the update, @arcticicestudio. 

I've finally got around to ahving a play with this. I'm perfectly happy to just change the diff_inserted background to `#81a1c133` as per the vscode PR, but thought I would have a quick play with the alpha of the existing current colours first.

I set the alpha for diff_inserted and diff_modified (which also has issues with contrast) down to 50, and just for good measurre set the alpha for diff_deleted down to 80. The result seems much more legible to me:

| Before | After |
| :------: | :-------: |
| ![diff_with_100_alpha](https://user-images.githubusercontent.com/2954690/85211672-5cd70e80-b343-11ea-9014-cd1cf878a7ff.png) | ![diff_with_reduced_alpha](https://user-images.githubusercontent.com/2954690/85211755-34034900-b344-11ea-9633-ee5322154e23.png) |

What do you reckon?
