### ISSUE TITLE
Issues with PHP Syntax, string concatenation and statements

### ISSUE THREAD

**Issue by kedodrill** [arcticicestudio/nord-jetbrains#119]
Hi there,

First of all, thank you so much for creating this theme! I love it and I always apply it to any editor I use.

The most recent update that was published to the Jetbrains plugin marketplace a few hours ago seemed to have broken some PHP syntax for me, mostly (I think) string concatenation. Screenshots below.

Everything here seems to be fine.

![testclass](https://user-images.githubusercontent.com/41304094/74251322-f74e8380-4cb9-11ea-97f0-e9d168eacfc4.png)

This seems to be the main issue. See middle of screenshot for weird syntax highlighting.
I am not sure if accessors for objects was like that before (all white), but I do feel like maybe there was some color there?

![testnord](https://user-images.githubusercontent.com/41304094/74251326-fae20a80-4cb9-11ea-95cb-0e36f07234df.png)

Again, things here seem fine, accessing values from an array works great, so I think the concat might be the issue here?

![script](https://user-images.githubusercontent.com/41304094/74251335-fcabce00-4cb9-11ea-8d2a-a030c3c51230.png)

**EDIT** Additionally, the highlighting is completely greyed out when the array is inside statement blocks, screenshot below shows a foreach and a for loop.

![arraysyntax](https://user-images.githubusercontent.com/41304094/74255052-52cf4000-4cbf-11ea-86ce-b577d06054b0.png)

If you need anymore information please let me know. Thanks!

**Comment by arcticicestudio** [comment]
Hi @kedodrill :wave:, thanks for your contribution :+1:
Nice to see you like Nord :smile: 

You're not alone with this problem. After deploying the plugin to the _JetBrains Plugin Marketplace_ and updating most of my _markup_ related syntax elements, like links/URLs and bold text as well as some braces in code blocks are highlighted with wrong colors like on your screenshots.

This is a really **strange and absolutely annoying bug of the IDE's theme engine**. These elements were highlighted correctly while testing the changes made in version 0.10.0, but *+none of these changes are related in any way to _markup_ elements**. The **same problem now occurred multiple times after IDE minor and patch version updates** while no single line of code in the theme plugin itself has been changed. This drives me nuts :unamused:

I'll create a meta-issue to collect the information of all the already resolved tickets in this repository regarding this defect syntax highlighting. For many users the plugin "broke" without touching the plugins code.
Afterwards I will open a issue in the [JetBrains bug tracker][yt] so this can finally be fixed in the IDE itself. Maybe a quick workaround is to replace all the highlighting definitions in the Nord plugin where colors are inherited from other values and explicitly define them instead. This worked fine in the past and is currently the only solution to get around these problems.

[yt]: https://youtrack.jetbrains.com/issues/IDEA

**Comment by arcticicestudio** [comment]
Sometimes a quick workaround is also to disable and enable the plugin again. After a restart there's a 95% chance (sigh) that inherited color definitions are applied correctly :neutral_face:

**Comment by kedodrill** [comment]
@arcticicestudio Hi Sven, thanks for the quick response. I did go through and read #115, but I figured I'd go ahead and make a new issue because I thought that this was a new issue that was caused by that update. Are you saying it's on the Jetbrains side?

Sounds like a plan though, thanks for the information. Is that workaround something that I can do locally? Or are you talking about a quick bandaid solution for now?

I did disable and enable it first, then I uninstalled it, went through my files and deleted the package and reinstalled it. No luck :(

**Comment by arcticicestudio** [comment]
Wrote down the history and current situation of this problem in #120.

**Comment by kedodrill** [comment]
@arcticicestudio Awesome! Feel free to close this issue whenever you need to. If you need any other information from me let me know. Thank you :)

**Comment by arcticicestudio** [comment]
Thanks for your feedback :+1: 
Submitted #137 to fix this and many other highlighting problems, details are documented in #129.

**Comment by kedodrill** [comment]
Don't wanna clutter up your PR's or anything, so just wanted to confirm that everything seems to be working fine for me with the latest update (0.11.2)! :tada:

**Comment by arcticicestudio** [comment]
Don't worry, that's the main use case of the _comment box_ in issues and PRs. Feedback is always welcome :smile: 
Great to see it works for you now!
