### ISSUE TITLE
App uses dark mode on macOS when system is in light mode

### ISSUE THREAD

**Issue by kyleAsilver** [arcticicestudio/nord-jetbrains#147]
OS: macOS Catalina 10.15.3 
IntelliJ version: IntelliJ IDEA CE 2019.3.4

This may be a problem with IntelliJ and not with the theme plugin itself, but my system uses default / light mode and IntelliJ is the one app that uses the dark theme when Nord is enabled. The theme should be agnostic to system light or dark mode, and shouldn't override my system preferences.

<img width="871" alt="Screen Shot 2020-04-08 at 10 56 14 AM" src="https://user-images.githubusercontent.com/24855760/78799437-20bd2000-7988-11ea-9815-2686bf3e2856.png">

**Comment by arcticicestudio** [comment]
Hi @kyleAsilver :wave:, thanks for your contribution :+1:
This is the design of _Nord_. There is (currently) no _light_ mode or configurable appearance of it. You can [switch to one of the light themes][d] that ship with IntelliJ by default or install [another light theme from the JetBrains plugin registry][s].

Closing this issue for now since this is not a problem related to _Nord_, but feel free to let me know if I misunderstood your problem 😄 

[s]: https://plugins.jetbrains.com/search?headline=164-theme&search=light&tags=Theme
[d] https://www.jetbrains.com/help/idea/user-interface-themes.html
