### ISSUE TITLE
Hovering and closing tabs makes them unreadable if macOS has menu bar hidden

### ISSUE THREAD

**Issue by ricardoaugusto** [arcticicestudio/nord-jetbrains#152]
Issue happens when in full screen mode and disabled "Automatically show and hide the menu bar" in macOS System Preferences. Toggling "PHPStorm > Preferences > Appearance > Show tool window bars" has no effect. Issue goes away by reinstalling the plugin but comes back after a while. Fresh install of PHPStorm on macOS 10.15.4 and Nord 0.11.2. 

Please see the video below:

![nord](https://user-images.githubusercontent.com/7663281/80366215-4179e680-885f-11ea-84b0-35fdf78ba046.gif)

**Comment by arcticicestudio** [comment]
Hi @ricardoaugusto :wave:, thanks for your contribution :+1:

This looks like a bug in the IDE itself since rendering is not part of a theme. A theme almost only consists of color definitions for names of UI elements but only some of them can be changed regarding width/height in pixels.

Could you please try to reproduce the problem with any of the themes bundled with _PhpStorm_ by default, e.g. **Darcula** or **macOS Light**? If these themes have the same problem this should be reported to _JetBrains_ through the [PhpStorm bug tracker][bt].

[bt]: https://youtrack.jetbrains.com/issues/WI

**Comment by ricardoaugusto** [comment]
Hey @arcticicestudio, yes I could reproduce the bug with the bundled themes. It seems to be an IDE issue. Thanks!

**Comment by ricardoaugusto** [comment]
Just in case someone finds this issue, follow up here: https://youtrack.jetbrains.com/issue/WI-52735

**Comment by arcticicestudio** [comment]
Alright, thanks for reporting anyway and the issue reference 👍
