### ISSUE TITLE
Some html attributes have long underlines

### ISSUE THREAD

**Issue by shavz** [arcticicestudio/nord-jetbrains#154]
Hello,

I have been a long time darcula user. But, I love this theme and how easy it is on my eyes, especially as I get older.

A big problem for me (but not a showstopper) has been the large underlines for some html attributes. for example:

![image](https://user-images.githubusercontent.com/40373468/80659226-aafe2d00-8acb-11ea-999b-b6a4848aa192.png)

I wonder if this is something that can be fixed?

**Comment by arcticicestudio** [comment]
Hi @shavz :wave:, thanks for your contribution :+1:

It looks like this is the style applied for syntax warnings of active [intention actions][d]. Nord uses a bright color for warnings (`nord13`) and the underline font style to make the user draw attention to the problem.
You can customize the style by modifying the editor color scheme at **Preferences** → **Editor** → **Color Scheme** → **General** and searching for the “warnings“ scope.

<div align="center"><img src="https://user-images.githubusercontent.com/7836623/81145607-e474e380-8f76-11ea-86c4-2b791d6361c7.png" /></div>

❕ Please note that **modifying editor schemes of plugins will create a copy of the scheme** that is placed in your IDE options directory (`colors` folder) and that **this copy won't be updated when the plugin gets updated**. Unfortunately _JetBrains_ hasn't solved this "problem" which often caused issues in theme repositories regarding "non-working theme plugins" or "outdated styles". In order to update your copy you need either need to manually edit the theme files and add changes made to the plugin or delete the copy and re.create it with you custom style based on the latest plugin version.

[d]: https://www.jetbrains.com/help/idea/intention-actions.html

**Comment by shavz** [comment]
hi @arcticicestudio thanks for responding. That makes sense.
