### ISSUE TITLE
IdeaVim Visual mode select color is barely recognized

### ISSUE THREAD

**Issue by f1729** [arcticicestudio/nord-jetbrains#156]
Here I'm selecting 

`e.eql(clientIp);`

<img width="442" alt="Screen Shot 2020-05-14 at 3 19 03 PM" src="https://user-images.githubusercontent.com/23299193/81981876-868b7000-95f6-11ea-8938-9018bb519f65.png">

**Comment by bendardenne** [comment]
Agreed. The selection background needs to be darker or lighter, but either way it needs more contrast with the caret row color. The color suggested in the PR works well for me too.

**Comment by Tom1206** [comment]
I must say +1 on this one. This is really bad right now. It looks good with the low contrast, but it cripples the editing. I often replace, or drag and drop, by mistake part of my code because I didn't noticed it was selected.

**Comment by arcticicestudio** [comment]
Hi @f1729 :wave:, thanks for your report and PR :+1:

Like @Tom1206 already mentioned, this is a known problem or respectively a limitation of the IDE that I've described in #55.
I've already [submitted IDEA-215064](https://youtrack.jetbrains.com/issue/IDEA-215064) in order to propose a better highlighting for selections.
Anyway, using the style implemented in #157 requires some more testing with syntax elements that also use `nord8` as foreground color. It might end up in merging the foreground color with the background color resulting in unreadable text.
If it works fine it can be merged because my hope that my submitted proposal gets implemented for the _JetBrains_ IDEs is currently pretty low.
