### ISSUE TITLE
Colors look "washed out" on Ubuntu 20.04 and Archlinux

### ISSUE THREAD

**Issue by mvettosi** [arcticicestudio/nord-jetbrains#178]
Hello, I don't see this reported anywhere but on both my linux setups, the editor color scheme looks very less bright than in the provided screenshots:
![intellijNordTheme](https://user-images.githubusercontent.com/36518528/133430437-63f07fb7-44d0-4113-87e8-5a5ef702f350.png)

Tested on:
Android Studio Arctic Fox | 2020.3.1 Patch 1
Build #AI-203.7717.56.2031.7621141, built on August 7, 2021
Runtime version: 11.0.10+0-b96-7249189 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-84-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: PlantUML integration, com.arcticicestudio.nord.jetbrains, Lombook Plugin, com.intellij.marketplace, idea.plugin.protoeditor, wu.seal.tool.jsontokotlin, com.thoughtworks.gauge, org.jetbrains.kotlin, org.intellij.plugins.markdown
Current Desktop: ubuntu:GNOME

**Comment by arcticicestudio** [comment]
Hi @mvettosi :wave:

This doesn't look like a problem of the theme but a result of your local setup and hardware. As you already described in the issue title the colors "look" different, but in fact the color codes defined by the theme are the same on every OS and IDE. You can verify this by using an application like [Gpick][1] to get the color that is rendered and compare it to the colors defined by this theme, [e.g. class names][2]. Normally they should both match, but if not then it is a sign that you're running into the (kind of famous) problem of [color space][3] differences. The reason for this can be different, for example your monitor is runs a specific color profile or your systems rendering engine (e.g. ["Mutter" on GNOME][4] or [`wlroots` on Sway][5]) is configured with a different color appereance.
In general the different methods of interpreting the [RGB color model][6] is a well-known problem in the digital design and computer graphics (including games) industry and they will never be a one-to-rule-them-all standard. I know that it is often kind of frustrating because I also run multiple Linux systems on my desktop computer where all of them use different window manager and renders/compositors, but I switched to macOS as my main productivity system which has a great concept of visualizating colors. The fact that the screenshots of this theme look that crisp is because they were made on a [Apple Retina display][7] which provide a really high quality due to a higher pixel density and a "really natural" color feeling.

Long stoey short: The is nothing that can be done from the side of this theme but only on the user side by trying to get a setup that uses a "natural" and color rich rendering, e.g. macOS or through good configurations for the systems rendering engine (software-side) and the used monitor (hardware-side).

[1]: http://www.gpick.org
[2]: https://github.com/arcticicestudio/nord-jetbrains/blob/4049a946/resources/themes/nord.xml#L901-L905
[3]: https://en.wikipedia.org/wiki/Color_space
[4]: https://en.wikipedia.org/wiki/Mutter_(software)
[5]: https://github.com/swaywm/wlroots
[6]: https://en.wikipedia.org/wiki/RGB_color_model
[7]: https://en.wikipedia.org/wiki/Retina_display

**Comment by mvettosi** [comment]
Thank you for the kind and detailed explanation!
I will definitely look into my local setup then.
Cheers
