### ISSUE TITLE
Filename hard to read when tab was selected

### ISSUE THREAD

**Issue by wingyplus** [arcticicestudio/nord-jetbrains#197]
From screenshot below:

<img width="197" alt="Screen Shot 2565-06-09 at 11 55 57" src="https://user-images.githubusercontent.com/484530/172767550-b8a2e909-0c15-4015-88ca-ce3fb3817cd8.png">

File name is quite hard to read when tab was selected.

**Comment by svengreb** [comment]
Hi @wingyplus 👋🏼 , thanks for your contribution :+1:

This is already a known problem that is tracked in #57, please subscribe to this issue for more details and updates. The cause is related to VCS ignored files and unfortunately a well-known regression or better named a missing feature from the theme API to better handle situations where multiple color are combined.
Also maybe see #106 that includes some workarounds from other users.
