### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by GauthierPLM** [arcticicestudio/nord-jetbrains#35]
The Python language is not properly supported: many element uses the default style and don't match with the colour theme.

<img width="714" alt="capture d ecran 2018-03-20 a 10 27 27" src="https://user-images.githubusercontent.com/2579741/37630865-24e01f50-2c2a-11e8-9124-2dfd134de070.png">

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

Which JetBrains IDE are you using (IntelliJ IDEA, PyCharm, WebStorm ...), which edition (_Community_- or _Ultimate_) and which version?

**Comment by GauthierPLM** [comment]
```
PyCharm 2018.1 EAP (Professional Edition)
Build #PY-181.4203.13, built on March 14, 2018
PyCharm EAP User
Expiration date: April 13, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.3
```

So PyCharm Professional Edition 2018.1.

**Comment by Alby407** [comment]
Any progress on Python Syntax? :)

**Comment by arcticicestudio** [comment]
I'm currently really busy working on [Nord Docs](https://github.com/arcticicestudio/nord-docs) so I've had no time to reproduce this problem. Anyway, I use the PyCharm _Community Edition_ often and it works fine out-of-the-box™️. If the problem is related to the _Professional Edition_ I've to set it up locally to test it, but I'm curious since all JetBrains IDEs are using the same theme syntax and at least the rules for generic language element should apply.

@GauthierPLM sorry for the late reply, there are many GitHub notifications each day and he one for this issue was sinking in the crowd. Are you still affected by the problem or have you been able to solve it? Might also be a configuration problem. Can you please try to install the theme from the [JetBrains plugin repository](https://plugins.jetbrains.com/plugin/10321-nord-color-scheme)?

**Comment by GauthierPLM** [comment]
Hi,

I indeed still have the issue, which should be present in PyCharm Community too. I used a fresh install of PyCharm Pro to test, without any modification of the settings, on version 2018.3.

The issues are the same. I installed the theme using the plugin from the plugin marketplace in the IDE.

I think it's caused by the settings being defined only for python and not relying on general language settings. You'll have to override them manually in the theme.

Also, note that you can get a free license if you are working on an Open Source project (such as this one).

**Comment by akking** [comment]
![image](https://user-images.githubusercontent.com/10442067/50291486-57d68d80-0434-11e9-8790-9dca2f2ea144.png)
This will work.
