### ISSUE TITLE
Provide Semanthic Highlighting colors

### ISSUE THREAD

**Issue by GauthierPLM** [arcticicestudio/nord-jetbrains#36]
Currently, defaults colours of Sementic  Highlighting don't match the theme. It would be nice if the colour scheme was providing matching colours.

**Comment by arcticicestudio** [comment]
I've tested the highlighting and I have decided not to implement the styles. The problem is that Nord uses `nord4` for variables/constants/objects (including font styles for special cases like _static_ elements), but the IntelliJ's _Semantic Highlighting_ feature requires at least 5 different (colorful) colors to call it “rainbow colors“. **This would break Nord's highlighting styles since the option would be automatically enabled as soon as the used editor color scheme provides one or more `RAINBOW_COLOR*` key** where the asterisk stand for the numbers `1`  to `5`.

Therefore this feature should only be enabled by the user who can then decide which colors to use to achieve the _rainbow color highlighting_. All of [Nord's colors are documented on the website][d] so they can be used if desired.

[d]: https://www.nordtheme.com/docs/colors-and-palettes
