### ISSUE TITLE
Current line and current selection could use a bit more contrast

### ISSUE THREAD

**Issue by axelitus** [arcticicestudio/nord-jetbrains#37]
I'm using the latest stable PHPStorm 2018.1.6 version and I think that it would be better to increase the contrast between the current line and the current selection because currently, it's hard to distinguish them:
![image](https://user-images.githubusercontent.com/732441/42329146-a97ed9fe-8035-11e8-93cf-65c4fd67b75e.png)
(the selected word is **function** on line 36)

Also, the comments are hard to read. I think a color like the one I have set in vim would work very nicely (which is a little bit brighter):
![image](https://user-images.githubusercontent.com/732441/42329420-4312c18e-8036-11e8-8b18-15d599efefe2.png)

For it I have this setting in my `.vimrc` file:
```vim
let g:nord_comment_brightness = 12
```

**Comment by arcticicestudio** [comment]
Thanks for your contribution 👍 
I'll see how to improve the recognizability of the selected text on the current line, maybe the selection will be brighter to stand out from the background color.

Regarding the comment color: There is arcticicestudio/nord#94 that deals with improving the contrast of comments for all port projects. It'll be implemented for this project as soon as the decision has been made.

**Comment by seraphlive** [comment]
I find "snowstorm" region highlight style in the Emacs version of Nord theme looks kind of cool. I'm thinking maybe we can use that as a reference. Just not sure if it can be easily implemented in jetbrain's editors. :)

**Comment by arcticicestudio** [comment]
@seraphlive Unfortunately there is no way to implement theme configurations since all definitions are simply XML and JSON files. It is not possible to implement any logic like functions for conditions based on user configurations. Emacs on the other hand are defined in Lisp so they can implement logic based on settings made by the user.

@axelitus The comment color contrast was finally increased in #41 and released in [version 0.4.0][v4]. I'll close this issue for now until there is either a way to implement theme configurations or the background color of the currently active cursor line can make use of color opacity (alpha layer). 

[v4]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.4.0

**Comment by arcticicestudio** [comment]
@axelitus I've submitted [IDEA-215064](https://youtrack.jetbrains.net/issue/IDEA-215064) that requests an implementation of the highlighting feature like in VS Code: Hide the background color of the active line when selecting text.

**Comment by axelitus** [comment]
@arcticicestudio great to hear! Hopefully, JetBrains gets this done, as it is a nice idea that would great without messing up with the color palette. I've given it the first thumbs up!
