### ISSUE TITLE
UI Theme not showing in PhpStorm 2019.1

### ISSUE THREAD

**Issue by axelitus** [arcticicestudio/nord-jetbrains#46]
I have installed Nord Color Scheme in PhpStorm 2019.1 and the UI theme option is not shown in the dropdown:
![image](https://user-images.githubusercontent.com/732441/56599698-b10a2580-65bc-11e9-9ef1-bc3e545a709e.png)

The Editor color scheme works fine.

**Comment by axelitus** [comment]
On the Plugin MArket page (and in IDE) it shows that it still version 0.4.0. Could this be the issue?
![image](https://user-images.githubusercontent.com/732441/56600031-7359cc80-65bd-11e9-8f26-a7784d6b74ce.png)

**Comment by axelitus** [comment]
I've probably confirmed it is an issue that version 0.4.0 is still being downloaded. I've extracted the Nord.jar in the plugins folder and the plugin.xml shows this:
![image](https://user-images.githubusercontent.com/732441/56600655-d0a24d80-65be-11e9-8d6a-3b6abc129689.png)

Which is not the latest 0.5.0 version of the file.

Is it being reviewed by JetBrains or is it not yet published in the MarketPlace?

**Comment by axelitus** [comment]
I've managed to compile it from source using IntelliJ Community and now it is showing the correct version:
![image](https://user-images.githubusercontent.com/732441/56604837-7e662a00-65c8-11e9-9fb9-9284f91b88f0.png)

Wow! The UI is beautiful, I'll enjoy working with this theme!

**Comment by arcticicestudio** [comment]
Compiling from source should work fine.
There are some problems deploying version 0.5.0 to the JetBrains Plugin Repository. It complains about an unmatching "Plugin XML ID" which was auto-generated by an older IntelliJ version. I've used the ID I'd like to use for the new UI & editor scheme, but while deploying the new version it'll deny the file due to the ID mismatch.
[I'm in contact with JetBrains through their Twitter account](https://twitter.com/arcticicestudio/status/1120629680061784064) to get some more details about this ID and if it is possible to modify it without breaking the plugin since the auto-generated ID (`color.scheme.Nord`) is really ugly and should be `com.arcticicestudio.nord.jetbrains` to match package domain model.

**Comment by Alby407** [comment]
Are there any instructions on how to compile from source? Unfortunately, there is no section in the README.

**Comment by axelitus** [comment]
No there aren't.

1. Just download the source and extract it anywhere in your file system.
![image](https://user-images.githubusercontent.com/732441/56620661-50481080-65ef-11e9-8444-1d11f9061802.png)

2. Install [JetBrains IntelliJ 2019.1+](https://www.jetbrains.com/idea) and create a new project
![image](https://user-images.githubusercontent.com/732441/56620765-a917a900-65ef-11e9-995d-c15e0b6ee4d4.png)

3. Select `IntelliJ Platform Plugin` as the project type and hit `Next`.
![image](https://user-images.githubusercontent.com/732441/56620525-d021ab00-65ee-11e9-883f-cd8dcb1af8d3.png)

4. Fill the project info as shown below (the name should be `nord-jetbrains` and the location should be where you extracted the project) and click `Finish`:
![image](https://user-images.githubusercontent.com/732441/56620888-0f043080-65f0-11e9-96ea-53d83ab9d119.png)

5. You will be prompted to overwrite the `nord-jetbrains.iml` file, click `Yes` (the file is the default module file for a Jetbrains Plugin anyways):
![image](https://user-images.githubusercontent.com/732441/56621024-889c1e80-65f0-11e9-8dbc-ea03889076a7.png)

6. Click on `Build > Build Project`:
![image](https://user-images.githubusercontent.com/732441/56621076-bd0fda80-65f0-11e9-8de6-a14bdf18b557.png)
A new `out` folder will be created:
![image](https://user-images.githubusercontent.com/732441/56621101-cf8a1400-65f0-11e9-99fb-4eeac12d481b.png)

7. Now click on `Build > Prepare All Plugin Modules For Deployment`:
![image](https://user-images.githubusercontent.com/732441/56621129-ea5c8880-65f0-11e9-9208-ce978d0cbdf5.png)

8. Ensure the `nord-jetbrains` module is selected and click `Next`:
![image](https://user-images.githubusercontent.com/732441/56621161-1415af80-65f1-11e9-9278-d0ff034642db.png)
A new file `nord-jetbrains.jar`should be created.

9. Copy the `nord-jetbrains.jar` file to `~/.PhpStorm2019.1/config/plugins` folder:
![image](https://user-images.githubusercontent.com/732441/56621246-6fe03880-65f1-11e9-9cc2-08f005014358.png)

10. Restart PhpStorm and enjoy!
![image](https://user-images.githubusercontent.com/732441/56621280-8ab2ad00-65f1-11e9-8442-437246643f24.png)

**Comment by Alby407** [comment]
Big thanks to you!! Btw what icon theme are you using? (Sorry for OT, but it looks really awesome) :)

**Comment by axelitus** [comment]
I'm using Ubuntu with Arc-Dark theme and [Paper](https://snwh.org/paper) iconset.

**Comment by arcticicestudio** [comment]
@axelitus Thanks for the detailed guide 👍 , I've planned to add one to the README but postponed it until all docs and assets are moved over to the website. There are some references and descriptions in #43 including links to official guides from JetBrains that I've used to transform the theme into a plugin.

**Comment by axelitus** [comment]
I found that guide and it served me as a basis, but I still struggled to know what I was doing (or should be doing) because I had never used IntelliJ, nor build a Jetbrain Plugin. So I wanted to give a step-by-step for newcomers like me.

I think (but I have not tested, nor am I sure) the same could be done as in previous versions that pack certain files directly into a jar (as a jar is basically a zip, it could be as easy as to zip the needed files in the needed structure and rename the file with .jar extension). Don't know if the build process does something different though, so maybe even IntelliJ is not needed.

**Comment by axelitus** [comment]
For all of you who don't want to follow the IntelliJ path I've created a bash script that packages the plugin: https://gist.github.com/axelitus/15186e4da4a39cced9d59dc885964db8

Just download it to the nord-jetbrains source code folder, give it execute permissions and run:

```bash
./build.sh
```

It requires either the `jar` command (you need to install the JDK for this) or the `zip` command.

Tested in Ubuntu 18.10 but it should work across many distros and versions that support bash.

**Comment by axelitus** [comment]
@arcticicestudio Previously there was a `build.sh` command, why has it been removed?

Was it because it did not make it through the theme->plugin conversion? Or was it something else?

**Comment by arcticicestudio** [comment]
The build script was removed because it is not necessary anymore and won't include auto-generated metadata that'll be added to the JAR file. There are also some checks that run when IntelliJ packages the plugin files like a correct Plugin XML ID and plugin icons.
Users shouldn't really care about how to build the plugin since it can be easily installed with all of JetBrain's IDEs using the [official plugin repository](https://plugins.jetbrains.com) that is available from within the application itself. This allows to install Nord with one mouse click and also updates the plugin automatically when new updates are available.

Anyway, I'll add the guide to the Nord website if users want to play around with the plugin or modify it.

**Comment by arcticicestudio** [comment]
Also the latest version 0.5.0 has been [deployed to the plugin repository](https://plugins.jetbrains.com/plugin/10321-nord) and will be available when the plugin passes the upload checks.
Please note that it is required to uninstall and install the plugin again if you're using a version of the theme less or equal to 0.4.0 since [the Plugin XML ID was changed](https://twitter.com/arcticicestudio/status/1120629680061784064) to match the naming scheme.

Please see the [release announcement on Twitter](https://twitter.com/arcticicestudio/status/1121126357164015617) and [additional info tweet](https://twitter.com/arcticicestudio/status/1121127453223792642) for some more details.

**Comment by axelitus** [comment]
Agreed, the manual installation was just because the repository version wasn't updated. Once its published this shouldn't be needed.

**Comment by mattfletcher** [comment]
I am still being offered 0.4.0 in the marketplace, is it normal for it to take this long to process?

**Comment by axelitus** [comment]
Are you on the latest version? (2019.X+ is needed).

I'm on PhpStorm 2019.1 and have no problems at all, it is already on the Marketplace:
![image](https://user-images.githubusercontent.com/732441/57083996-11851b00-6cbf-11e9-912c-b50c06630967.png)

**Comment by arcticicestudio** [comment]
@mattfletcher Please note that it is required to uninstall and install the plugin again if you're using a version of the theme less or equal to 0.4.0 since [the Plugin XML ID was changed](https://twitter.com/arcticicestudio/status/1120629680061784064) to match the naming scheme.

Please see the [release announcement on Twitter](https://twitter.com/arcticicestudio/status/1121126357164015617) and [additional info tweet](https://twitter.com/arcticicestudio/status/1121127453223792642) for some more details.

**Comment by arcticicestudio** [comment]
@axelitus As of _Nord Docs_ [version 0.12.0] the [docs and assets of _Nord JetBrains_ have been migrated][d]. There's also a [development guide][g] now for users who like to customize the plugin or build it from source.

[v]: https://github.com/arcticicestudio/nord-docs/releases/tag/v0.12.0
[d]: https://www.nordtheme.com/ports/jetbrains
[g]: https://www.nordtheme.com/docs/ports/jetbrains/development
