### ISSUE TITLE
Library root file colors distracting / unreadable

### ISSUE THREAD

**Issue by rwev** [arcticicestudio/nord-jetbrains#51]
![image](https://user-images.githubusercontent.com/40538419/57813981-5bdeb100-772f-11e9-86bd-8de8cfacc331.png)

![image](https://user-images.githubusercontent.com/40538419/57813990-69943680-772f-11e9-8b8a-9578fc6440ef.png)

![image](https://user-images.githubusercontent.com/40538419/57814786-11aaff00-7732-11e9-81b0-8304cdcf5ff9.png)

Additionally, when these filetypes are list in the project file tree or in file search results, they are the bright yellows and greens are easily confused with the selected / highlighted file. Recommend darker yellow (green) backgrounds that offer better contrast with the white library (test) filenames.

All in all, I'm blown away by the scheme so far. Absolutely beautiful with nearly perfect unity between the colors. Great work. 

IntelliJ Idea 2019.1.2 (Ultimate Edition) Build #UI-191.7141.44

**Comment by arcticicestudio** [comment]
> Duplicate of #47

Hi @rwev , thanks for the reports :+1: 
This has already been reported in #47 and is related to the _File Colors_ setting of IntelliJ. Like commented in #47 JetBrains theme API should be improved to handle such cases, but if there is no possible change in the near future I'll remove the color definitions from the theme to fix these bright highlightings.
In the meantime please see this comment in order to fix the problem: https://github.com/arcticicestudio/nord-jetbrains/issues/47#issuecomment-486661998

**Comment by arcticicestudio** [comment]
Resolved in #53
