### ISSUE TITLE
GoLand 2019.2 display wrong color for go code

### ISSUE THREAD

**Issue by smonv** [arcticicestudio/nord-jetbrains#69]
I tried Nord plugin with GoLand 2019.2 but couldn't get north-bluish color like image demo at README.md

I felt like the color still come from Dracula instead of Nort

<img width="808" alt="Screen Shot 2019-07-31 at 16 09 42" src="https://user-images.githubusercontent.com/8962973/62199650-16d12f00-b3ae-11e9-83ec-fcc4a06e4dfb.png">
<img width="737" alt="Screen Shot 2019-07-31 at 16 12 27" src="https://user-images.githubusercontent.com/8962973/62199651-16d12f00-b3ae-11e9-94cc-577170b2d4d9.png">

**Comment by arcticicestudio** [comment]
Hi @smonv :wave:, thanks for your contribution :+1:

I've also upgraded to 2019.2 some minutes ago and can confirm that the update broke the highlighting. I've also noticed some component using the default _Darcula_ styles like tabs and the auto completion popup after updating to 2019.1.3. Seems like they changed the theme UI and editor color scheme API without really notifying theme authors or at least documenting the changes including an announcement as blog post or via Twitter :disappointed: 

I've marked the issue as critical and taking a look into it right now. Requires me to set up a fresh container installation to debug the changes that are automatically applied by the IDE to the underlying theme files as soon as 2019.2 starts so hopefully I can track down the root cause.

**Comment by smonv** [comment]
Thanks for quick response, hope you find the cause soon.

Currently I can manage change color scheme similar to image demo by manual
tick inherit color in every setting line of go.

**Comment by arcticicestudio** [comment]
One cause might be the new [introduction of support for 20+ new languages][rl] through the integration of [TextMate][tm]. I currently scrawl through all the [EAP builds][eap] of [2019.1][] and [2019.2][] to find a ticket that might contain more information about the changes.

[rl]: https://www.jetbrains.com/idea/whatsnew/#v2019-2-editor
[tm]: https://macromates.com
[eap]: https://confluence.jetbrains.com/display/IDEADEV/EAP
[2019.1]: https://confluence.jetbrains.com/display/IDEADEV/IDEA+2019.1+EAP
[2019.2]: https://confluence.jetbrains.com/display/IDEADEV/IDEA+2019.2+EAP

**Comment by arcticicestudio** [comment]
Alright, first results: found YouTrack issue [IDEA-201007][] that resulted in the implementation of more detailed linting output, e.g. showing deprecated theme API keys :tada: 
At least this explains the "corrupted" styles of some IDE UI elements like tabs and the auto-completion popup and some more: The theme keys are deprecated and have been replaced with new ones resulting in a fallback value of the parent scheme `darcula`.

![gh-69-research-youtrack-idea-201007-schema-deprecation-linting](https://user-images.githubusercontent.com/7836623/62220347-30737600-b3b0-11e9-98b5-8950cfa76b15.png)

I guess for the Go syntax highlighting there are also new keys or they changed the behaviour of not inheriting the global value by default so there are now many `GO_` editor color scheme keys missing.

[idea-201007]: https://youtrack.jetbrains.com/issue/IDEA-201007

**Comment by arcticicestudio** [comment]
@smonv I've implemented the missing color scheme keys for Go in #70, seems like they changed the default inheritance behavior of some syntax definitions so some of the keys simply used the values from the parent _Darcula_ theme.

**Comment by smonv** [comment]
Thanks for detailed explanation and the fixes. Hope you can fixes UI key change and release soon

**Comment by smonv** [comment]
I just tried Nord 0.7.0 with Clion 2019.2 and seem like it display color correctly with UI auto-complete and rust code.

<img width="1022" alt="Screen Shot 2019-08-01 at 09 11 16" src="https://user-images.githubusercontent.com/8962973/62260531-75dd8500-b43c-11e9-91ed-270e690e5dc3.png">

**Comment by arcticicestudio** [comment]
Java works fine too using IntelliJ 2019.2, so it looks like only some languages are affected. Going to check all bundled _Community & _Ultimate Edition_ languages as well as some popular other language plugins, maybe it requires more PRs for the next version to be sure it works for 2019.2.

**Comment by arcticicestudio** [comment]
@smonv [Version 0.8.0 has been released][v] but not published to the JetBrains plugin registry yet since I'd like to get some test feedback if it works fine for other IDEs except IntelliJ. Could you please [download the plugin JAR file from the release notes][d], uninstall the Nord plugin from the marketplace and [install the plugin locally from disk][l] to test if everything works fine now?

[v]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.0
[d]: https://github.com/arcticicestudio/nord-jetbrains/releases/download/v0.8.0/nord-jetbrains.jar
[l]: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by smonv** [comment]
@arcticicestudio Thank for the quick fix.

<img width="653" alt="Screen Shot 2019-08-02 at 16 08 29" src="https://user-images.githubusercontent.com/8962973/62358894-e620ff00-b53f-11e9-9922-d19691bec567.png">
<img width="1014" alt="Screen Shot 2019-08-02 at 16 09 17" src="https://user-images.githubusercontent.com/8962973/62358903-ec16e000-b53f-11e9-8039-abbe74160989.png">

I just tried with GoLand 2019.2 and seem like color displayed correctly.

One thing seem off is when I reinstall plugin, I don't automatically change my font to `Source Code Pro` like version 0.7.0. It just set editor font to `Menlo`

<img width="1014" alt="Screen Shot 2019-08-02 at 16 11 30" src="https://user-images.githubusercontent.com/8962973/62359040-35ffc600-b540-11e9-92eb-d3466e46b566.png">

**Comment by arcticicestudio** [comment]
@smonv Great, I've deployed v0.8.0 to the marketplace some hours ago and it was already passed JetBrains validation process so you can uninstall the manually installed plugin again and use the normal installation process through the marketplace. Thanks again for testing :muscle:

**Comment by smonv** [comment]
Thank you so much. That was very quick fix.

**Comment by arcticicestudio** [comment]
You're welcome, it's one of the largest port projects and also my daily driver to develop Go/Rust/React/Java so it bothered me too :smile:

**Comment by smonv** [comment]
@arcticicestudio Sorry for bother you on weekend but after update to Nord 0.8.0, my auto-complete not showing anything until I manually click to it box or press arrow up. I'm not sure this problem because of my code, my IDE setting or colorscheme. I never got any problem like this before.

<img width="801" alt="Screen Shot 2019-08-04 at 10 27 11" src="https://user-images.githubusercontent.com/8962973/62419111-4e3c2600-b6a3-11e9-8774-54d2a7566898.png">

**Comment by arcticicestudio** [comment]
@smonv This has already been reported in #88 and fixed in #89. The patch version [0.8.1][] has also already been released and deployed to the JetBrains marketplace, but it'll take some time until is passes JetBrains validation process because I guess they won't work on saturdays/sundays for this :smile: 

[0.8.1]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.1
