### ISSUE TITLE
Suggestions not showing properly

### ISSUE THREAD

**Issue by jaumecapdevila** [arcticicestudio/nord-jetbrains#92]
Hi!
After upgrading to the latest version of the plugin **0.8.0**, I've noticed that the suggestions are not properly displayed until you use the arrows or click control + space (check attached screenshots).

PHPStorm version: **2019.2**

<img width="692" alt="Screenshot 2019-08-07 at 10 44 58" src="https://user-images.githubusercontent.com/7687573/62608773-ca7f7500-b900-11e9-931a-318a0ad97a1d.png">
<img width="685" alt="Screenshot 2019-08-07 at 10 45 09" src="https://user-images.githubusercontent.com/7687573/62608774-ca7f7500-b900-11e9-8ee0-c74f03fb77e9.png">

Thanks in advance, let me know if you need more info.

**Comment by arcticicestudio** [comment]
Hi @jaumecapdevila :wave:, thanks for your report :+1:
This was a known problem reported in #88 that was fixed in #89 an has been merged in to the already deployed release version [0.8.1][] some days ago. The plugin update is available from the JetBrains marketplace, but it was pending some days due to the weekend and JetBrains process to validate plugin updates manually (quality control, prevention of malicious plugins etc.).
You can update to the latest version from within PHPStorm using the [builtin plugin marketplace UI][m].

[0.8.1]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.1
[m]: https://www.jetbrains.com/help/idea/managing-plugins.html#de4e8f8c

**Comment by jaumecapdevila** [comment]
As you said, now is working as expected 😄 

Thanks @arcticicestudio !!
